### ISSUE TITLE
 the app  very slow for 1~5 second when init

### ISSUE THREAD

**Issue by hpgood** [openfl/extension-admob#14]
the app  very slow for 1~5 second when execute  the functoin "AdMob.initAndroid" or  "AdMob.initIOS".
is the bug of admob?
ps:
https://www.google.com/?gws_rd=ssl#newwindow=1&q=++Admob+slow+++FPS

**Comment by fbricker** [comment]
Hi, this may be related to google admob... hard to tell (sounds logic that including an ad network can lower down your app if you have an old smartphone or a really slow internet connection, but it shouldn't do that on a fast smartphone with good internet access).

Is this happening on android and iOS to you? (calling AdMob.initIOS does nothing on android, so I assume you're testing on iOS and Android with the same result).

If this is the case, maybe your game is consuming too many resources, and calling admob is just the drop of water that saturates your smartphones :/

On any case, admob works on background creating threads, so I don't think there's much to do from inside the extension. I'll be closing this issue now (if you find some evidence that the extension is responsible of the lag instead of admob itself, or have some clue on how to fix this, please let us know and we'll reopen the case).

Thanks!
Federico
