### ISSUE TITLE
dlopen failed in Android 6, using target-sdk-version="23"

### ISSUE THREAD

**Issue by vega-7** [openfl/extension-admob#21]
Hi fbricker ,.

FIrst of all thanks for share your code/extensions  im currently using two of them ( extension-share and extension-Admod) on my puzzle game "hulapuzzle", (check the credits) they works marvelous in Android 2.3 ,Android 4 and 5.  

on Android 6 , i'm heaving trouble fixing this error java.lang.unsatisfiedLinkError dlopen failed Library "long_path_to/libc.so", apparently in some part of the apk generation the compiler dont copy the libc.so and also dont create a correct relative path to this library.

The funny thing about this is,..  i figured out  how fix this , and i can do the fix downgrading the   target-sdk-version from 23 to 22, but google dont let me publish the apk with this change, because i had already publish the apk targeting the version 23 of the sdk.

Can you please help me with this, in internet appear something about migrating from openssl to boringssl  but i cant  follow/understand this migration, on your code i cant find any reference to openssl ,. in google i cant find anything related with this error or is ambiguous , and i dont have any idea about how to fix this. i think you know how to do this, cause your game daktylos works fine without any trouble on android 4 and 6 , . .

Thanks in advance

**Comment by fbricker** [comment]
Hi, last version of daktylos was published with SDK 19 I guess, so we didn't cross this issue yet.
About SDK 23, we're using it on a new game we're working on without issues, but we're using openfl/lime legacy (I don't know if you're using next or legacy, maybe this changes things a little).

Anyway, I doesn't seems like this issue is related to this extension. Maybe you should address this directly on slack ( https://openfl.slack.com/messages/help/ ) to see if someone had the same issue :/

**Comment by vega-7** [comment]
Hi fbricker ,  i have fixed the error, i did reinstalling the new Android SDK and NDK , and updating the haxe paths thought haxelib setup  ,. and using / in the paths insteads \ , . . Now is working perfectly in android 6.0.

thanks for your help and again thanks for the extensions.

**Comment by fbricker** [comment]
Great! 👍
