### ISSUE TITLE
Cannot install Google Play services

### ISSUE THREAD

**Issue by cooljith91112** [openfl/extension-admob#24]
According to latest google play services **Revision 30+** google_play_services_lib is not available in the extras folder. When ever compiling for android target I'm getting an error **AndroidManifest.xml** not found. Is there any workaround for the issue? Any manual override?

**Comment by And-0** [comment]
I've run into the same issue. I found a [thread in the OpenFL Community](http://community.openfl.org/t/solved-extension-admob-compile-error/7736) which might help you out. It did fix the issue for me, however I'm now getting a different error:

```
C:\Development\Android SDK\tools\ant\build.xml:597: The following error occurred while executing this line:
C:\Development\Android SDK\tools\ant\build.xml:649: The following error occurred while executing this line:
C:\Development\Android SDK\tools\ant\build.xml:694: null returned: 1
```

I'm currently investigating whether it's related or just something on my end.

**Comment by fbricker** [comment]
Hi, we've just created a new library called "extension-googleplayservices-basement" and published updates to all libraries using this library to use the new one.

extension-googleplayservices-basement contains the smaller libraries in which google separated, and will include just the required pieces to your projects according to each extension requirements.

This is good, since you'll be saving some MB on your games 👍 

So, to be clear: 
* Just doing haxelib upgrade will upgrade google play games, amazon sns, facebookads, and admob extensions to the last SDK versions (no API changes were made, so you shouldn't have issues at all). 
* extension-googleplayservices-lib is official deprecated (we'll leave it working for some time until most people migrates to the new extension).
* Now the SDKs comes inside the extensions (you won't need to download anything from your Android Device Manager).
