### ISSUE TITLE
check if Ads are Ready (cached)

### ISSUE THREAD

**Issue by xmorpher** [openfl/extension-admob#6]
Admob has a feature to cache Ads, and a method to check if it was cached/loaded... 
This is implemented in the Adobe Air / Admob too, 
Do you think is possible to implement this?
Regards

**Comment by fbricker** [comment]
Hi, such a feature is not under our top priorities right now, but it doesn't seem hard to implement as we're already caching ads and checking this inside the extension, so exposing this feature may be simple :)

**Comment by fbricker** [comment]
Hi, we've released a new version of the extension that uses the cached information in order to display the interstitial or not.
Also, when calling to display interstitials, you'll receive a true or false (that will let you know if the ad was displayed or not). If the ad is not displayed, it means one of two things:
1) The ad was not cached yet (or there was some loading error)
2) You are using the parameters that came with showInterstitial to control the ad frequency, and the extension is refusing to display the ad since it's too soon according to your prefferences.

Please let me know if this addresses your needs :)

Thanks!

**Comment by xmorpher** [comment]
Yes, it's very useful, thanks!
