### ISSUE TITLE
Listening for ad events, changing the unit ID

### ISSUE THREAD

**Issue by afro-ninja** [openfl/extension-admob#8]
Hi fbricker, thanks again for this extension. I had a few basic questions for you:

- I saw the issue regarding checking to see if an ad is ready. From my understanding this is not currently implemented. Do you have a preferred way of handling this?

For example, right now I can basically only call 
AdMob.showInterstitial(0);
and wait to see what happens. if the ad isn't loaded, nothing happens at all. Should I create my own 'Ad is loading' window, and time it out after X seconds? That way the user understands that the app at least tried to load an ad.

- Related to the above question: do ads only get one chance to display on screen? If I call 'showInterstitial' and nothing happens, do I have to worry about the ad randomly showing up later?

- Lastly, am I free to change the unit id during runtime, after it is initially set? I would like to randomize the unit id each time so I can share profits between myself and my partner. As soon as one ad is finished, can I make another call to initAndroid()/initIOS() and just pass in a new id? Not sure if this will result in unintended behavior.

Thanks!

**Comment by fbricker** [comment]
Hi, about the loading events, I'll try to add them soon. Anyway, I've fixed one issue and now the interstitials loads when you call init the first time (this won't fix your case 100% but will help I guess).

About changing the AdUnit during runtime, I'm not sure if google will allow that. I've asked some people from AdMob support team and they've told me that AdMob allows just one Account per App (so you can have multiple ad units, but all of them needs to come from the same account).

I'm not sure if this is correct (since it's probably that the person who answered didn't understand the idea, or that he even didn't ask to the right person inside AdMob), but this is the information I had from Google about this (and that's why I didn't bother in allowing the extension to switch ad-units).

If you do have some information or anything from google saying that this is allowed, I'll modify the extension for sure :)

Thanks!

**Comment by afro-ninja** [comment]
I spoke with my publisher today and they claimed they have already published several apps that make use of changing the AdUnits at runtime. Whether or not they are *supposed* to do it is another issue.

Worst case scenario they demand I implement this, can I just keep making new calls to init?

**Comment by fbricker** [comment]
Hi, sorry for the late response here. Are you still needing this?
We can add this to the next release if it's useful :)

**Comment by fbricker** [comment]
I've closed the issue since I guess you no longer need this feature. If you need it, please re-open it.

**Comment by afro-ninja** [comment]
Oh, sure thing. Sorry for not responding. Thanks!

On Sun, Apr 10, 2016 at 12:30 PM, Federico Bricker <notifications@github.com
